# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macos-latest'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'



steps:

#- task: InstallAppleCertificate@2
#  inputs:
#    certSecureFile: cert.p12
#    certPwd: 'test'

#- task: InstallAppleProvisioningProfile@1
#  inputs:
#    provProfileSecureFile: '6ffac825-ed27-47d0-8134-95fcf37a666c.mobileprovision'

- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false


#- task: CopyFiles@2
#  inputs:
#    contents: '**/*.app'
#    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1