# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macos-latest'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'



steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: cert1.p12
    certPwd: 'test'
    
- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'Sober_Development_Profile-2.mobileprovision'

#- task: Xcode@5
#  inputs:
#    actions: 'build'
#    configuration: '$(configuration)'
#    sdk: '$(sdk)'
#    scheme: '$(scheme)'
#   packageApp: false
#    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: '$(configuration)'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    packageApp: true
    archivePath: '$(build.artifactStagingDirectory)'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    exportOptions: 'plist'
    exportOptionsPlist: '$(build.artifactStagingDirectory)'
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.app'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1